### ISSUE TITLE
flat image calculation code

### ISSUE THREAD

**Issue by avani17101** [tnestmeyer/reflectance-filtering#1]
Hello,
Is there no code released for the calculation of flat image as mentioned in paper Section 5.2 Using a flattened image as guidance/

If there is a code release can you please point it out?
Thanks

**Comment by tnestmeyer** [comment]
As mentioned in the paper: 
See [7] for how to solve the resulting optimization problem. We will refer to the result of this L1-flattening optimization from now on also simply as flat.

The references tell you this is

[7] S. Bi, X. Han, and Y. Yu. An L1 image transform for edge-
preserving smoothing and scene-level intrinsic decomposi-
tion. ACM Trans. Graph., 34(4):78:1–78:12, July 2015.

Searching for this leads you to the official code (I also used), which can be found under: https://github.com/sai-bi/L1Flattening

**Comment by avani17101** [comment]
Thanks, it worked
